### ISSUE TITLE
和另一个 LogQA 有什么关系啊？

### ISSUE THREAD

**Issue by chenryn** [xichie/LogSay#1]
https://github.com/LogQA-dataset/LogQA 之前看到过这个，也是基于 loghub 几个数据集做what/where 之类的问答。有什么关系么？

另外，两个项目都是给定单条日志做一问一答。目前业界有没有那种输入整个文件几万条日志，直接进行自然语言问答的研究啊？相当于跳过 text to sql这种查询语言层的中转，以及不限于单条，偏总结和推理性的问答？

**Comment by xichie** [comment]
这都是我们的工作，它们是一个递进的关系。现在这个工作可以支持一些简单的数值推理，比如求和、计数操作。 
一次性输入上万条log，这个确实是一个挑战，也是我们目前研究的方向。

**Comment by xichie** [comment]
> 


> https://github.com/LogQA-dataset/LogQA 之前看到过这个，也是基于 loghub 几个数据集做what/where 之类的问答。有什么关系么？
> 
> 另外，两个项目都是给定单条日志做一问一答。目前业界有没有那种输入整个文件几万条日志，直接进行自然语言问答的研究啊？相当于跳过 text to sql这种查询语言层的中转，以及不限于单条，偏总结和推理性的问答？

这都是我们的工作，它们是一个递进的关系。现在这个工作可以支持一些简单的数值推理，比如求和、计数操作。 一次性输入上万条log，这个确实是一个挑战，也是我们目前研究的方向。

**Comment by chenryn** [comment]
👍 期待
